- name: Set net.ipv4.ip_nonlocal_bind
  sysctl:
    name: net.ipv4.ip_nonlocal_bind
    value: 1
    sysctl_set: yes
    state: present
    reload: yes

- name: install haproxy
  apt:
    name: haproxy
    state: latest
  tags:
    - haproxy