---
# test root
- name: Make root test
  hosts: mesos-masters
  become: true
  roles:
    - name: Make root test
      role: mesos/test
  tags: [test]

- name: 1. Open Firewall For Galera
  become: true
  hosts: galera-nodes
  roles:
    - name: Open access to Galera cluster
      role: ufw
      ufw_port_for_inventory_hostnames:
        - port: 3306
          hosts: "{{ groups['galera-nodes'] }}"
        - port: 4567
          hosts: "{{ groups['galera-nodes'] }}"
        - port: 4568
          hosts: "{{ groups['galera-nodes'] }}"
        - port: 4444
          hosts: "{{ groups['galera-nodes'] }}"
  tags: [ufw]

# mysql prepare
- name: Prepare all for install
  hosts: galera-nodes
  become: true
  roles:
    - name: MySQL Prepare all for install
      role: mysql/prepare

# mysql-haproxy
- name: install and configure mysql-galera
  hosts: galera-nodes
  become: true
  roles:
    - name: install and configure mysql-haproxy
      role: mysql/galera
      
