---
# test root
- name: Make root test
  hosts: mesos-masters
  become: true
  roles:
    - name: Make root test
      role: mesos/test
  tags: [test]

- name: 1. Open Firewall For Mesos
  become: true
  hosts: mesos-all
  roles:
    - name: Open access to Galera cluster
      role: ufw
      ufw_port_for_inventory_hostnames:
        - port: 3306
          hosts: "{{ groups['mesos-all'] }}"
        - port: 4567
          hosts: "{{ groups['mesos-all'] }}"
        - port: 4568
          hosts: "{{ groups['mesos-all'] }}"
        - port: 4444
          hosts: "{{ groups['mesos-all'] }}"
  tags: [ufw]
