---
# test root
- name: Make root test
  hosts: galera-nodes
  become: true
  roles:
    - name: Make root test
      role: mysql/test
  tags: [test]

# mysql prepare
- name: Prepare all for install
  hosts: galera-nodes
  become: true
  roles:
    - name: MySQL Prepare all for install
      role: mysql/prepare

# mysql-haproxy
- name: install and configure mysql-galera
  hosts: galera-nodes
  become: true
  roles:
    - name: install and configure mysql-haproxy
      role: mysql/galera