---
# tasks file for roles/ssh_access
- name: create group admin
  group:
    state: present
    name: admin

- name: create users
  user:
    state: present
    name: "{{ item.key }}"
    group: admin
  with_dict: sshusers

- name: allow group 'admin' to use passwordless sudo
  lineinfile:
    state: 'present'
    dest: '/etc/sudoers'
    regexp: '^%ADMIN ALL\='
    line: '%ADMIN ALL=(ALL) NOPASSWD:ALL'
    validate: 'visudo -cf %s'

- name: create key directory
  file:
    path: /etc/ssh/authorized_keys
    state: directory
    owner: 0
    group: 0
    mode: 0755

- name: upload user key
  copy:
    content: "{{ item.value.key }}"
    dest: "/etc/ssh/authorized_keys/{{ item.key }}"
    owner: 0
    group: 0
    mode: 0644
  with_dict: sshusers

- name: sshd configuration file update
  template:
    src: sshd_config.j2
    dest: /etc/ssh/sshd_config
    backup: yes
    owner: 0
    group: 0
    mode: 0644
    validate: '/usr/sbin/sshd -T -f %s'
  notify:
    - restart sshd
