
- name: Install keepalived
  apt:
    name: keepalived
    state: latest
  tags:
    - keepalived
    
- name: Create keepalived.conf from template
  template:
    src: keepalived.conf.j2
    dest: "{{ keepalived_settings.directories.conf }}"
