- name: Create the directories for marathon conf
  file:
    path: "/etc/marathon/conf"
    state: directory
    mode: 0755

- name: Include init Mesos Masters
  include: master.yml
  when: mesos_role == "master"

- name: Include init Mesos Slaves
  include: slave.yml
  when: mesos_role == "slave"