- name: Generating quorum.status count
  template:
    src: quorum.status
    dest: /etc/mesos-master/quorum.status

- name: Generating mesos ip for node
  template:
    src: ip.j2
    dest: /etc/mesos-master/ip

- name: Generating mesos hostname for node
  template:
    src: hostname.j2
    dest: /etc/mesos-master/hostname