- name: Generating mesos slave ip for node
  template:
    src: ip.j2
    dest: /etc/mesos-slave/ip

- name: Generating mesos hostname for node
  template:
    src: hostname.j2
    dest: /etc/mesos-slave/hostname